INSERT INTO "My Books" 
("Title", "House", "Room", "Skill Book")
VALUES ("2920, Frostfall, V10", "Tundra Homestead", "Bedroom", TRUE),
	   ("2090, Last Seed, V8", "Tundra Homestead", "Bedroom", TRUE), 
	   ("2090, Second Seed, V5", "Tundra Homestead", "Bedroom", TRUE),
	   ("2090, Sun's Dawn, V2", "Tundra Homestead", "Bedroom", TRUE),
	   ("2090, Sun's Height, V7", "Tundra Homestead", "Bedroom", FALSE),
	   ("A Dance in Fire, V1", "Tundra Homestead", "Bedroom", FALSE),
	   ("A Dance in Fire, V3", "Tundra Homestead", "Bedroom", FALSE),
	   ("A Dance in Fire, V4", "Tundra Homestead", "Bedroom", FALSE),
	   ("A Gentleman's Guide To Whiterun", "Tundra Homestead", "Bedroom", FALSE),
	   ("A Hypothetical Treachery", "Tundra Homestead", "Bedroom", TRUE),
	   ("Aedra and Daedra", "Tundra Homestead", "Bedroom", FALSE),
	   ("Ahzirr Traajijazeri", "Tundra Homestead", "Bedroom", FALSE),
	   ("Before the Ages of Man", "Tundra Homestead", "Bedroom", TRUE),
	   ("Beggar Prince", "Tundra Homestead", "Bedroom", FALSE),
	   ("Biography of Barenziah, V1", "Tundra Homestead", "Bedroom", FALSE),
	   ("Biography of Barenziah, V2", "Tundra Homestead", "Bedroom", FALSE),
	   ("Biography of Barenziah, V3", "Tundra Homestead", "Bedroom", FALSE),
	   ("Brief History of the Empire, V1", "Tundra Homestead", "Bedroom", FALSE),
	   ("Brief History of the Empire, V2", "Tundra Homestead", "Bedroom", FALSE),
	   ("Brief History of the Empire, V4", "Tundra Homestead", "Bedroom", FALSE),
	   ("Business Ledger Copy", "Tundra Homestead", "Bedroom", FALSE),
	   ("Chimarvamidium", "Tundra Homestead", "Bedroom", TRUE),
	   ("Bjormund's Diary", "Tundra Homestead", "Bedroom", FALSE),
	   ("Darkest Darkness",  "Tundra Homestead", "Bedroom", FALSE),
	   ("Death Blow of Abernanit", "Tundra Homestead", "Bedroom", TRUE),
	   ("Dragon Language: Myth No More", "Tundra Homestead", "Bedroom", FALSE),
	   ("Frontier, Conquest", "Tundra Homestead", "Bedroom", FALSE),
	   ("Galerion the Mystic", "Tundra Homestead", "Bedroom", FALSE),
	   ("Gods and Worship", "Tundra Homestead", "Bedroom", FALSE),
	   ("Great Harbingers", "Tundra Homestead", "Bedroom", FALSE),
	   ("Herbane's Bestiary: Hagravens", "Tundra Homestead", "Bedroom", FALSE),
	   ("Horker Attacks", "Tundra Homestead", "Bedroom", FALSE),
	   ("Horror of Castle Xyr", "Tundra Homestead", "Bedroom", TRUE),
	   ("Immortal Blood", "Tundra Homestead", "Bedroom", FALSE),
	   ("Killing - Before You're Killed", "Tundra Homestead", "Bedroom", FALSE),
	   ("Kolb and the Dragon", "Tundra Homestead", "Bedroom", FALSE),
	   ("Life of Uriel Septim VII", "Tundra Homestead", "Bedroom", FALSE),
	   ("Light Armor Forging", "Tundra Homestead", "Bedroom", TRUE),
	   ("Liminal Bridges", "Tundra Homestead", "Bedroom", TRUE),
	   ("Magic From the Sky", "Tundra Homestead", "Bedroom", FALSE),
	   ("Mixed Unit Tactics", "Tundra Homestead", "Bedroom", FALSE),
	   ("Mysterious Akavir", "Tundra Homestead", "Bedroom", FALSE),
	   ("Myths of Sheogorath", "Tundra Homestead", "Bedroom", FALSE),
	   ("Necromancer's Journal", "Tundra Homestead", "Bedroom", FALSE),
	   ("Mystery of Talara, Part 4", "Tundra Homestead", "Basement", TRUE),
	   ("Mystery of Talara, V1", "Tundra Homestead", "Basement", FALSE),
	   ("Mystery of Talara, V4,", "Tundra Homestead", "Basement", TRUE),
	   ("Nords Arise!", "Tundra Homestead", "Basement", FALSE),
	   ("Notes on the Lunar Forge", "Tundra Homestead", "Basement", FALSE),
	   ("Pirate King of the Abecean", "Tundra Homestead", "Basement", FALSE),
	   ("Report: Disaster at Ionith", "Tundra Homestead", "Basement", FALSE),
	   ("Skyrim's Rule", "Tundra Homestead", "Basement", FALSE),
	   ("Song of the Alchemists", "Tundra Homestead", "Basement", TRUE),
	   ("Songs of the Return Vol 19", "Tundra Homestead", "Basement", FALSE),
	   ("The Aetherium Wars", "Tundra Homestead", "Basement", FALSE),
	   ("The Arcturian Heresy", "Tundra Homestead", "Basement", FALSE),
	   ("The Art of War Magic", "Tundra Homestead", "Basement", TRUE),
	   ("The Black Arrow, V1", "Tundra Homestead", "Basement", FALSE),
	   ("The Black Arrow, V2", "Tundra Homestead", "Basement", TRUE),
	   ("The Book of Daedra", "Tundra Homestead", "Basement", FALSE),
	   ("The Book of the Dragonborn", "Tundra Homestead", "Basement", FALSE),
	   ("The Cake and the Diamond", "Tundra Homestead", "Basement", FALSE),
	   ("The City of Stone", "Tundra Homestead", "Basement", FALSE),
	   ("The Code of Malacath", "Tundra Homestead", "Basement", FALSE),
	   ("The Firmament", "Tundra Homestead", "Basement", FALSE),
	   ("The Firsthold Revolt", "Tundra Homestead", "Basement", FALSE),
	   ("Advances in Lockpicking", "Goldenhills Plantation", "Bedroom", TRUE),
	   ("Alchemist'a Journal", "Goldenhills Plantation", "Bedroom", FALSE),
	   ("Argonian Account, Book 1", "Goldenhills Plantation", "Bedroom", FALSE),
	   ("Argonian Account, Book 2", "Goldenhills Plantation", "Bedroom", FALSE),
	   ("Arvel's Journal", "Goldenhills Plantation", "Bedroom", FALSE),
	   ("Assassin's Journal", "Goldenhills Plantation", "Bedroom", FALSE),
	   ("Beggar", "Goldenhills Plantation", "Bedroom", TRUE),
	   ("Nightingales: Fact or Fiction", "Goldenhills Plantation", "Bedroom", FALSE),
	   ("Tattered Journal", "Goldenhills Plantation", "Bedroom", FALSE),
	   ("The Armorer's Challenge", "Goldenhills Plantation", "Bedroom", TRUE),
	   ("The Great War", "Goldenhills Plantation", "Bedroom", FALSE),
	   ("The Holds of Skyrim","Goldenhills Plantation", "Bedroom", FALSE),
	   ("The Ransom of Zarek", "Goldenhills Plantation", "Bedroom", FALSE),
	   ("The Real Barenziah, V1", "Goldenhills Plantation", "Bedroom", FALSE),
	   ("The Red Year, Vol. II", "Goldenhills Plantation", "Bedroom", FALSE),
	   ("The Song of Pelinial, V6", "Goldenhills Plantation", "Bedroom", FALSE),
	   ("The Song of Pelinial, V7", "Goldenhills Plantation", "Bedroom", FALSE),
	   ("The Warrior's Charge", "Goldenhills Plantation", "Bedroom", TRUE),
	   ("The Wolf Queen, V1", "Goldenhills Plantation", "Bedroom", TRUE),
	   ("The Wolf Queen, V2", "Goldenhills Plantation", "Bedroom", FALSE),
	   ("The Wolf Queen, V3", "Goldenhills Plantation", "Bedroom", FALSE),
	   ("The Wolf Queen, V4", "Goldenhills Plantation", "Bedroom", FALSE),
	   ("The Wolf Queen, V5", "Goldenhills Plantation", "Bedroom", FALSE),
	   ("Theif", "Goldenhills Plantation", "Bedroom", TRUE),
	   ("Twin Secrets", "Goldenhills Plantation", "Bedroom", TRUE),
	   ("Whiterun Home Decorating Guide", "Goldenhills Plantation", "Bedroom", FALSE),
	   ("Withershins", "Goldenhills Plantation", "Bedroom", TRUE),
	   ("Yellow Book of Riddles", "Goldenhills Plantation", "Bedroom", FALSE)
;